# Rakefile for running tests

require 'rake/testtask'

Rake::TestTask.new do |t|
  t.name = 'spec'
  t.pattern = '*_spec.rb'
end

Rake::TestTask.new do |t|
  t.name = 'test'
  t.pattern = '*_test.rb'
end

task default: [:test, :spec]
